version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.9.2
    container_name: zookeeper
    restart: on-failure
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network
    volumes:
      - zookeeper_data:/bitnami/zookeeper/data
      - zookeeper_logs:/bitnami/zookeeper/logs

  kafka:
    image: bitnami/kafka:3.6.2
    container_name: kafka-server
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    volumes:
      - kafka_data:/bitnami/kafka/data
      - kafka_logs:/bitnami/kafka/logs

  flume:
    image: apache-flume:1.11.0
    container_name: flume-agent
    # environment:
      # - FLUME_AGENT_NAME:docker
    volumes:
      - ./flume-conf:/opt/apache-flume/conf
    networks:
      - kafka-network
    depends_on:
      - kafka
    command: [ "/opt/apache-flume/bin/flume-ng", "agent", "--name", "agent", "--conf", "conf", "--conf-file", "/opt/apache-flume/conf/config.conf" ]
    # command: [ "/opt/apache-flume/bin/flume-ng", "agent", "-n", "${FLUME_AGENT_NAME}", "-c", "conf", "-f", "/opt/apache-flume/conf/config.conf" ]
    
    
    mem_limit: 512m
    cpu_shares: 512

  kafka-ui:
    image: provectuslabs/kafka-ui:53a6553765a806eda9905c43bfcfe09da6812035
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=puc
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  zookeeper_data:
  kafka_data:
  zookeeper_logs:
  kafka_logs:

